# Generated by Django 4.2.7 on 2026-04-05 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('location', 'Location'), ('preference', 'Preference'), ('habit', 'Habit'), ('fact', 'Fact'), ('relationship', 'Relationship')], max_length=50)),
                ('current_value', models.TextField()),
                ('previous_value', models.TextField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.8)),
                ('embedding_vector', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['entity'], name='voice_memor_entity_4e341a_idx'), models.Index(fields=['updated_at'], name='voice_memor_updated_8bd7cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversationTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.TextField()),
                ('qwen_intent', models.JSONField()),
                ('gpt_response', models.TextField(blank=True, null=True)),
                ('spoken_response', models.TextField()),
                ('memory_action', models.CharField(blank=True, max_length=50)),
                ('memory_updated', models.BooleanField(default=False)),
                ('latency_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voice.conversationsession')),
            ],
        ),
    ]
